#!/bin/bash

DEPENDENCIES="clap -F cargo"
USAGE="usage: create-day [<day-number>]\n\tCreates a new cargo project with the name day<day-number> with\n\ta template for solutions"
PWD=$(pwd)
if [ $PWD != "/home/bcheatha/advent-of-code-23" ]; then
	echo "Must run in advent-of-code directory!"
	exit 1
fi

if [ -z "$1" ]; then
	echo -e $USAGE
	exit 1
fi

DAY="day$1"

if [ -d "$DAY" ]; then
	echo "Directory \"$DAY\" already exists!"
	exit 1
fi

cargo new $DAY
rm $DAY/src/main.rs
cp template.rs $DAY/src/main.rs
cd $DAY
cargo add $DEPENDENCIES
cd ..
